package org.real.controller;

import org.real.model.Credential;
import org.real.model.Permission;
import org.real.model.User;
import org.real.service.UserService;
import org.real.view.UserView;

import java.util.List;

public class UserController {
    private UserService service;

    public UserController() {
        this.service = new UserService();
    }

    public Integer add(String firstname, String lastName, String dni, String email) {
        User user = new User();

        user.setFirstName(firstname);
        user.setLastName(lastName);
        user.setDni(dni);
        user.setEmail(email);

        // updating the user with the ID generated by the db
        user = service.save(user);

        return user.getId(); // returns the ID to future uses
    }

    public List<User> readAll() {
        return service.getAll();
    }

    public User read(Integer userId) {
        return service.getById(userId);
    }

    public Integer update(Integer userId, String newFirstName, String newLastName, String newDni, String newEmail) {
        User toModify = read(userId);

        toModify.setFirstName(newFirstName);
        toModify.setLastName(newLastName);
        toModify.setDni(newDni);
        toModify.setEmail(newEmail);

        return service.update(toModify).getId();
    }

    public void deleteById(Integer userId) {
        service.deleteById(userId);
    }
}
